name: Deploy Infraestructura AWS (PR4)

on:
  push:
    branches:
      - test
    paths:
      - 'infra/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set default.region us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Inicializar y aplicar Terraform
        run: |
          terraform -chdir=infra init
          terraform -chdir=infra apply -auto-approve

      - name: Exportar outputs de Terraform
        run: |
          terraform -chdir=infra output -raw ec2_public_ip > ec2_ip.txt
          terraform -chdir=infra output -raw rds_endpoint > db_host.txt

      - name: Subir outputs como artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: |
            ec2_ip.txt
            db_host.txt

      - name: Subir clave SSH como artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssh-key
          path: infra/pr4-key.pem



